env:
  browser: true
  commonjs: true
  es6: true
  jest: true
  node: true

extends:
  - plugin:prettier/recommended
  - eslint:recommended
  - plugin:react/recommended

parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 9
  ecmaFeatures:
    modules: true
    jsx: true
plugins:
  - prettier
  - react
