env:
  browser: true
  commonjs: true
  es6: true
  jest: true
  node: true

extends:
  - airbnb
  - eslint:recommended
  - plugin:prettier/recommended

parser: 'babel-eslint'
parserOptions:
  ecmaVersion: 9
  ecmaFeatures:
    modules: true
    jsx: true

plugins:
  - prettier
  - react

settings:
  react:
    version: 'detect'
